name: Sidali Free RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Configure Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok_folder
        .\ngrok_folder\ngrok.exe config add-authtoken 3GI4INFfmG1Xu0AXMNBSIuk212b_6pTRRtEFSd1nj5fHtJmhX
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user runneradmin Sidali2026!
    - name: Debug Ngrok (Find the Error)
      run: |
        Start-Process .\ngrok_folder\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow -RedirectStandardOutput "ngrok.log" -RedirectStandardError "ngrok.err"
        Start-Sleep -Seconds 5
        echo "===================================================="
        echo "🔥 واش راه يقول NGROK؟ 🔥"
        Get-Content ngrok.err
        Get-Content ngrok.log
        echo "===================================================="
        $response = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
        $url = $response.tunnels[0].public_url
        echo "الرابط: $url"
        Start-Sleep -Seconds 21600
