name: Sidali Free RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Configure Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok_folder
        .\ngrok_folder\ngrok.exe config add-authtoken 3GI4INFfmG1Xu0AXMNBSIuk212b_6pTRRtEFSd1nj5fHtJmhX
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user runneradmin Sidali2026!
    - name: Start Ngrok Tunnel and Get URL
      run: |
        Start-Process .\ngrok_folder\ngrok.exe -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 10
        $response = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
        $url = $response.tunnels[0].public_url
        $clean_url = $url -replace "tcp://", ""
        echo "===================================================="
        echo "🔥 السيرفر واجد يا بطل 🔥"
        echo "انسخ هاد الرابط وحطه في التطبيق ديريكت:"
        echo "$clean_url"
        echo "اليوزر: runneradmin"
        echo "المودباس: Sidali2026!"
        echo "===================================================="
        Start-Sleep -Seconds 21600
